#!/bin/sh

PKG_NAME=$(basename "$SYNOPKG_PKGDEST")
TARGET_DIR="/var/packages/$PKG_NAME/target"
UI_DIR="$TARGET_DIR/ui"
TEXTS_DIR="$TARGET_DIR/ui/texts"

# Remove spurious files injected by the package builder
rm -f "$UI_DIR/Makefile"
rm -f "$UI_DIR/ui"         # self-referencing symlink
rm -f "$TEXTS_DIR/strings" # strings file template

# Make scripts executable
chmod 755 "$TARGET_DIR/bin/drive_info.sh"
chmod 755 "$TARGET_DIR/cgi/drive_info.cgi"

exit 0
